# See https://jekyllrb.com/docs/configuration/default/
title: "روزنوشت‌های من"
motto: "می‌نویسم پس هستم"
author: Mehdi Sadeghi
email: sadeghi@mehdix.org

# the base hostname & protocol for your site without trailing slash
url: https://mystifying-benz-938b25.netlify.com
# the subpath of your site, e.g. /blog
baseurl: 

keywords: کامپیوتر برنامه‌نویسی وب
copyright: "Commons Attribution 4.0 International"

# A one liner that describes your blog
description: > # this means to ignore newlines
  سکوی انتشار مطالبی در مورد دانش تولید نرم‌افزار و ایده‌ها و علایق شخصی‌ام.

# Tell more about your blog here
long_description: >
  بچه که بودیم همیشه برای بازی خونه می‌ساختیم. حالا هم نمونه‌اش رو در وب ساختم.
  اینجا سکوی انتشار مطالبی در مورد دانش تولید نرم‌افزار و ایده‌ها و علایق شخصی‌ام است،
  بویژه راه‌حل‌های مهندسی که باعث رشد و پیشرفتم شده است و می‌تواند مورد استفاده دیگران هم قرار بگیرد.

# The tiny icon of the website
favicon: assets/img/favicon.png
permalink: :title.html
timezone: Europe/Berlin

paginate: 3
paginate_path: /page:num/

tag_page_layout: tag_page
tag_page_dir: tag

collections:
  projects:
    output: true

# Set to `static` or `disqus`.
comments:
  enabled: true
  type: static
  recaptcha: false
  static:
    avatar:
      visible: true
  disqus:
    # Used if the `comment_system` is set to `disqus`
    shortname: ''

# Setting this will add the analytics snipped.
#google_analytics_id:

# A unique identifier for your website's feed. If not set
# the url of the website will be used instead. Using URL is
# recommended if you own a domain name.
#atom_feed_id: urn:uuid:1e7d9dd8-29e4-475d-adc5-17494fb80445

# If you run a feedburner newsletter set this. Not recommended
# since sooner or later Google will kill this service.
#feedburner_id:

lang: fa_IR

# Footer stuff
twitter:
  username: mehdisadeghii
github:
  username: mehdisadeghi
  repository: jekyll-theme-mehdix-rtl

# Footer logo will disappear if not set.
#logo: assets/img/me.png

exclude:
- scripts
- cache
- .bundle
- reply-mail-hook
- CONTRIBUTING.md
- netlify.toml
- LICENSE
- env.sh
- screenshot.png
- jekyll-theme-mehdix-rtl.sublime-project
- jekyll-theme-mehdix-rtl.sublime-workspace
- travis.yml
- jekyll-theme-mehdix-rtl.gemspec
- rebuild_comments.py
- README.md
- renovate.json
- '*.gem'


# Set default post layout
defaults:
-
  scope:
    path: ""
    type: "posts"
  values:
    layout: "post"
